domains:
- domain: daily.stafre.se
  type: PRIMARY
functions:
- envs:
  - key: CLIENT_ID
    scope: RUN_AND_BUILD_TIME
    type: SECRET
    value: EV[1:PNqu6cefMc7rM43mqJg1cg8yk6DZUhdU:SSmCJYT4Ggy7ndMXaa3vITcm9ykd26CLH7IrEXFm]
  - key: CLIENT_SECRET
    scope: RUN_AND_BUILD_TIME
    type: SECRET
    value: EV[1:Plfpv3pBqqaWvQ7BrSqPvblkTFJ/pkZa:fQ/2PTdwxyCxyRU+TfLzxDUJV012bMJqMtkvZWk/swgCtZeVeRcLTygptQ==]
  github:
    branch: master
    deploy_on_push: true
    repo: gish/wr-latest-daily-redirect
  name: redirect
  routes:
  - path: /redirect
  source_dir: /
name: wr-latest-daily-redirect
region: ams
services:
- dockerfile_path: .do/Dockerfile
  github:
    branch: master
    deploy_on_push: true
    repo: gish/wr-latest-daily-redirect
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xxs
  name: lb
  routes:
  - path: /
  - path: /r/weightroom
