functions:
- envs:
  - key: CLIENT_ID
    scope: RUN_AND_BUILD_TIME
    type: SECRET
    value: EV[1:PNqu6cefMc7rM43mqJg1cg8yk6DZUhdU:SSmCJYT4Ggy7ndMXaa3vITcm9ykd26CLH7IrEXFm]
  - key: CLIENT_SECRET
    scope: RUN_AND_BUILD_TIME
    type: SECRET
    value: EV[1:Plfpv3pBqqaWvQ7BrSqPvblkTFJ/pkZa:fQ/2PTdwxyCxyRU+TfLzxDUJV012bMJqMtkvZWk/swgCtZeVeRcLTygptQ==]
  github:
    branch: master
    repo: gish/wr-latest-daily-redirect
    deploy_on_push: true
  name: wr-latest-daily-redirect
  routes:
  - path: /wr-latest-daily-redirect3
  source_dir: /
name: wr-latest-daily-redirect
region: ams
