---
name: "deploy"

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: production
    strategy:
      matrix:
        node-version: [17]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Build
        run: npm ci && npm run build --if-present
      - name: Add package build
        uses: EndBug/add-and-commit@v9
        with:
          add: './packages'
          message: 'chore(build): add package build'
          push: 'master'
