---
name: "deploy"

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repo
        uses: actions/checkout@v2
      - name: Push to dokku
        uses: dokku/github-action@master
        with:
          git_remote_url: "ssh://dokku@${{ secrets.DOKKU_HOST }}:22/wr-latest-daily"
          ssh_private_key: ${{ secrets.SSH_KEY }}
