---
name: "deploy"

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - master
  workflow_dispatch:
  workflow_run:
    workflows: ["merge-pr"]
    branches: [master]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Updating website.
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/www/wr-latest-daily-redirect
            git pull --force origin master
            npm install
            npm run build
            pm2 restart wr-latest-daily-redirect
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: #logs
          SLACK_COLOR: ${{ job.status }}
          SLACK_TITLE: wr-latest-daily deployment
          MSG_MINIMAL: commit
